services:
  sql.service:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    networks:
      - rabbit-network

networks:
  rabbit-network:
    external: true